[tool.poetry]
name = "grader-helper"
version = "0.1.9"
description = "Functions to help manage assignments from UL which are hosted on Brightspace"
authors = ["Kevin O Malley"]
license = "MIT"
readme = "README.md"
packages = [{include = "grader_helper"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
pathlib = "^1.0.1"
openpyxl = "^3.1.2"
ipykernel = "^6.29.4"
xlwings = "^0.31.1"
tqdm = "^4.66.4"
numpy = "^1.26.4"


[tool.poetry.group.dev.dependencies]
sphinx = "^7.3.7"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
