name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine

      - name: Clean previous builds
        run: Remove-Item -Recurse -Force dist, build

      - name: Build the package
        run: |
          hatch build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.GH_PYPI_TOEKN }}
        run: |
          twine upload --verbose dist/*


